In [2]:
import pandas as pd
import numpy as np
from sklearn.cluster import DBSCAN
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_samples, silhouette_score

In [3]:
data = pd.read_csv("../data/test_data.csv")
data = data.drop("Unnamed: 0", axis=1)
print(data)

       Excel  IBM SPSS Statistics  KNIME  MATLAB  Python  Python Pandas  R  \
0          0                    1      1       1       0              0  1
1          1                    1      1       1       1              1  0
2          0                    1      1       1       1              1  1
3          1                    1      1       1       1              1  1
4          0                    1      1       1       0              1  0
5          1                    1      1       1       1              1  1
6          0                    1      1       1       1              1  1
7          0                    1      1       1       0              1  1
8          0                    0      1       1       1              1  1
9          0                    1      1       0       0              0  0
10         0                    1      1       1       1              1  1
11         1                    0      1       1       1              1  1
12         0                    1      1       1       0              0  1
13         0                    1      1       1       1              1  0
14         0                    1      1       0       0              0  1
15         0                    1      1       1       1              1  1
16         1                    1      1       1       0              1  0
17         0                    1      1       1       1              1  1
18         0                    1      1       0       0              1  1
19         0                    1      1       0       0              0  1
20         0                    1      1       1       1              1  1
21         1                    1      1       1       1              1  1
22         0                    1      1       1       0              0  1
23         0                    1      1       1       0              0  0
24         0                    1      1       0       0              0  1
25         1                    1      1       1       0              1  1
26         1                    1      1       1       0              0  1
27         0                    1      1       1       0              0  0
28         1                    1      0       1       0              0  0
29         0                    1      1       0       0              0  1
...      ...                  ...    ...     ...     ...            ... ..
19651      1                    1      1       1       1              1  1
19652      1                    1      1       1       1              1  1
19653      1                    1      1       1       1              1  1
19654      1                    1      1       1       1              1  1
19655      1                    1      1       1       1              1  1
19656      1                    1      1       1       1              1  1
19657      1                    1      1       1       1              1  1
19658      1                    1      1       1       1              1  1
19659      1                    1      1       1       1              1  1
19660      1                    1      1       1       1              1  1
19661      1                    1      1       1       1              1  1
19662      1                    1      1       1       1              1  1
19663      1                    1      1       1       1              1  1
19664      1                    1      1       1       1              1  1
19665      1                    1      1       1       1              1  1
19666      1                    1      1       1       1              1  1
19667      1                    1      1       1       1              1  1
19668      1                    1      1       1       1              1  1
19669      1                    1      1       1       1              1  1
19670      1                    1      1       1       1              1  1
19671      1                    1      1       1       1              1  1
19672      1                    1      1       1       1              1  1
19673      1                    1      1       1       1              1  1
19674      1                    1      1       1       1              1  1
19675      1                    1      1       1       1              1  1
19676      1                    1      1       1       1              1  1
19677      1                    1      1       1       1              1  1
19678      1                    1      1       1       1              1  1
19679      1                    1      1       1       1              1  1
19680      1                    1      1       1       1              1  1

       Rapid Miner  SQL  Weka ...   Research  Beginner  Expert  Intermediate  \
0                1    1     1 ...          0         0       1             0
1                1    1     1 ...          1         1       0             0
2                1    1     1 ...          0         1       0             0
3                1    1     1 ...          0         1       0             0
4                1    0     1 ...          0         0       0             1
5                1    1     0 ...          1         1       0             0
6                1    0     1 ...          0         1       0             0
7                1    0     1 ...          0         1       0             0
8                1    1     1 ...          0         1       0             0
9                1    1     1 ...          0         1       0             0
10               1    1     1 ...          0         1       0             0
11               1    1     1 ...          0         1       0             0
12               0    0     1 ...          0         1       0             0
13               1    1     1 ...          0         1       0             0
14               1    1     1 ...          0         0       0             1
15               1    1     1 ...          0         1       0             0
16               1    0     1 ...          0         0       0             1
17               1    1     1 ...          0         1       0             0
18               1    1     1 ...          1         1       0             0
19               1    0     1 ...          1         1       0             0
20               1    1     1 ...          0         1       0             0
21               1    1     0 ...          0         1       0             0
22               1    1     1 ...          0         1       0             0
23               1    0     1 ...          0         0       1             0
24               1    0     1 ...          0         1       0             0
25               1    0     1 ...          0         1       0             0
26               1    1     1 ...          0         1       0             0
27               1    0     0 ...          0         0       0             1
28               1    1     1 ...          0         0       0             1
29               1    0     0 ...          0         1       0             0
...            ...  ...   ... ...        ...       ...     ...           ...
19651            1    1     1 ...          1         1       0             0
19652            1    1     1 ...          0         1       0             0
19653            1    1     1 ...          1         0       0             1
19654            1    1     1 ...          0         1       0             0
19655            1    1     1 ...          0         0       0             1
19656            1    1     1 ...          0         0       0             1
19657            1    1     1 ...          0         1       0             0
19658            1    1     1 ...          0         1       0             0
19659            1    1     1 ...          0         0       0             1
19660            1    1     1 ...          0         0       0             0
19661            1    1     1 ...          0         1       0             0
19662            1    1     1 ...          0         1       0             0
19663            1    1     1 ...          0         0       0             1
19664            1    1     1 ...          0         0       0             1
19665            1    1     1 ...          0         1       0             0
19666            1    1     1 ...          0         1       0             0
19667            1    1     1 ...          0         1       0             0
19668            1    1     1 ...          0         0       0             1
19669            1    1     1 ...          0         1       0             0
19670            1    1     1 ...          0         1       0             0
19671            1    1     1 ...          0         0       0             0
19672            1    1     1 ...          0         1       0             0
19673            1    1     1 ...          0         0       0             1
19674            1    1     1 ...          0         0       1             0
19675            1    1     1 ...          0         0       1             0
19676            1    1     1 ...          0         0       0             1
19677            1    1     1 ...          0         1       0             0
19678            1    1     1 ...          0         0       0             1
19679            1    1     1 ...          0         1       0             0
19680            1    1     1 ...          1         0       0             1

       Anaconda  College  Conference  Friends  School  Web
0             1        0           0        0       0    0
1             1        0           0        0       0    0
2             0        0           0        0       0    1
3             0        0           0        0       0    0
4             0        0           0        0       0    0
5             0        0           0        0       0    1
6             0        1           0        0       0    0
7             0        0           0        0       0    1
8             0        1           0        0       0    0
9             1        0           0        0       0    0
10            0        0           0        0       0    0
11            0        0           0        0       0    1
12            0        0           0        0       1    0
13            0        0           0        0       0    0
14            0        0           0        1       0    0
15            0        0           0        0       0    1
16            0        0           0        0       0    1
17            0        0           0        0       1    0
18            1        0           0        0       0    0
19            1        0           0        0       0    0
20            1        0           0        0       0    0
21            0        1           0        0       0    0
22            0        1           0        0       0    0
23            1        0           0        0       0    0
24            1        0           0        0       0    0
25            0        1           0        0       0    0
26            0        0           0        0       0    1
27            0        0           0        0       0    1
28            1        0           0        0       0    0
29            1        0           0        0       0    0
...         ...      ...         ...      ...     ...  ...
19651         0        0           0        0       0    1
19652         0        0           0        0       0    1
19653         0        0           1        0       0    0
19654         0        1           0        0       0    0
19655         0        0           0        0       0    1
19656         0        0           0        1       0    0
19657         0        0           0        0       0    1
19658         0        1           0        0       0    0
19659         0        1           0        0       0    0
19660         0        0           0        0       0    0
19661         0        0           0        0       0    1
19662         0        0           1        0       0    0
19663         0        0           0        0       0    1
19664         0        0           0        0       0    1
19665         0        0           0        0       0    0
19666         0        0           0        0       0    1
19667         0        1           0        0       0    0
19668         0        1           0        0       0    0
19669         0        0           0        0       0    0
19670         0        0           0        1       0    0
19671         0        0           0        0       0    1
19672         0        0           0        0       0    1
19673         0        0           0        0       0    1
19674         0        0           0        0       0    1
19675         0        0           0        0       0    0
19676         0        0           0        0       0    1
19677         0        1           0        0       0    0
19678         0        0           0        1       0    0
19679         0        0           0        0       0    1
19680         0        0           0        0       0    1

[19681 rows x 25 columns]

In [6]:
for n_clusters in range(2,10):
    clusterer = KMeans(n_clusters=n_clusters, random_state=1)
    cluster_labels = clusterer.fit_predict(data)

    silhouette_avg = silhouette_score(data, cluster_labels)
    print(silhouette_avg)

0.142300342872
0.089549073568
0.0980354632057
0.101846243464
0.0969515060408
0.0932527175764
0.101730885557
0.102770873381